### ISSUE TITLE
Surround Key setting broken in 0.6.0

### ISSUE THREAD

**Issue by dcalhoun** [gepoch/vim-surround#17]
My Surround Key setting (capital S) doesn't seem to be respected any more. It was working pre-0.6.0 release. Using the default key (lowercase s) binding does work.

#### Environment
- Mac OS X 10.10.3
- Atom 0.196.0
- vim-surrond 0.6.0

**Comment by gepoch** [comment]
Ah, I believe the name of the setting may have changed. Try updating your config again to use uppercase S, and see if that fixes it.

Sorry for the change. The method of specifying config schemas changed, and I wanted a better naming scheme going forward so that the other surround commands would play nicely in the config namespace..

**Comment by dcalhoun** [comment]
Yep, looks like you renamed "Surround Key" to "Surround Command". Unsetting the former and setting the latter seems to fix the issue. The "Surround Key" field is now no longer visible since I unset it.
