### ISSUE TITLE
[], {} not working on german keyboard

### ISSUE THREAD

**Issue by chapati23** [gepoch/vim-surround#25]
i'm guessing it has to do with the fact that on the german keyboard you have to use the following shortcuts to write brackets:

[ = alt + 5
] = alt + 6
| = alt + 7
{ = alt + 8
} = alt + 9
\ = alt + shift + 7

is the alt-key the problem?

you can probably test this by switching your keyboard layout to german via system preferences

**Comment by DrBones** [comment]
Hi, I have the same issue. 

Sorry for commenting on such an old Issue but I would love to use vim-surround with a German keyboard. I assume it is due to the way vim-surround's keymap generation is implemented as it actually looks for e.g. the "s [" combination which never happens as you have pointed out.

Did you find a successful workaround (apart from rebinding all the keys to "s alt-5" and so forth...) ?

I think it would be ideal if vim-surround would not listen to the key code pressed but to the actual character written, if this is possible but Atom has IMHO some issues with international keyboards in general so it might be worth waiting to see what happens upstream :)

**Comment by gepoch** [comment]
Hey @DrBones. vim-surround is implemented on vim-mode using atom's keymapping abstractions. It shouldn't rely on keycodes, as you say.

I did some digging, and it looks like this issue is arising from a bug in chromium that the atom team can't fix. See here: https://github.com/atom/atom-keymap/issues/37

**Comment by DrBones** [comment]
Wow, that was fast! Thanks gepoch, that looks like quite the long read but the package for localization might be worth a try. I will be digging in that direction as well.

P.S.: I think this could actually be closed since it probably is an issue with atom core or electron.
