### ISSUE TITLE
vim-mode-next support?

### ISSUE THREAD

**Issue by gepoch** [gepoch/vim-surround#28]
Hey everyone!

We have a lot of vim-mode-next plugins commenting on tickets lately. Currently, it's API is really close to vim-mode. There are no guarantees of this remaining the case, however.

Still, I would love to support it, as long it is within my means to do so! v0.8.0 takes a crack at it. Previously, you could only use vim-surround with vim-mode-next if you had vim-mode installed and disabled.

Now, you don't need the old vim-mode at all.

If the vim-mode-plus API should significantly diverge from vim-mode, and it becomes too much work to maintain API bindings to both, I'll be falling back to vim-mode.

Hopefully, that never happens :)

**Comment by bronson** [comment]
Very cool!  I don't picture vim-mode-next ever diverging too much from vim-mode because that would make merging irritating.  If you see incompatibilities, tell me, because it's probably a mistake.

Interestingly, with vim-mode's flurry of merged PRs last week, there's not much reason to run vim-mode-next anymore.  They're pretty close again.  Hope it stays that way, and vim-mode keeps merging PRs quickly.  We'll see!

**Comment by bronson** [comment]
Yes, thank you for closing.  I've switched to vim-mode-plus.  vim-mode is improving but still has a sizeable PR backlog.
